name: Pull Request

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests with coverage
        run: bun test --coverage

      - name: Check formatting
        run: bunx biome check

      - name: Type check
        run: bun run type-check

      - name: Build
        run: bun run build

      - name: Check build output
        run: |
          if [ ! -f "dist/index.js" ]; then
            echo "Build failed: dist/index.js not found"
            exit 1
          fi
          if [ ! -f "dist/index.mjs" ]; then
            echo "Build failed: dist/index.mjs not found"
            exit 1
          fi
          if [ ! -f "dist/index.d.ts" ]; then
            echo "Build failed: dist/index.d.ts not found"
            exit 1
          fi

      - name: Get bundle sizes
        id: bundle-size
        run: |
          echo "cjs=$(stat -f%z dist/index.js 2>/dev/null || stat -c%s dist/index.js)" >> $GITHUB_OUTPUT
          echo "esm=$(stat -f%z dist/index.mjs 2>/dev/null || stat -c%s dist/index.mjs)" >> $GITHUB_OUTPUT

      - name: Comment PR with test results
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const testStatus = '${{ job.status }}';
            const emoji = testStatus === 'success' ? '✅' : '❌';
            const cjsSize = '${{ steps.bundle-size.outputs.cjs }}';
            const esmSize = '${{ steps.bundle-size.outputs.esm }}';

            const formatBytes = (bytes) => {
              const kb = bytes / 1024;
              return kb < 1 ? `${bytes} B` : `${kb.toFixed(2)} KB`;
            };

            const body = `
            ## Test Results ${emoji}

            **Status**: ${testStatus}

            ### Checks
            - Tests: ${testStatus === 'success' ? 'Passed ✓' : 'Failed ✗'}
            - Format: ${testStatus === 'success' ? 'Passed ✓' : 'Failed ✗'}
            - Type check: ${testStatus === 'success' ? 'Passed ✓' : 'Failed ✗'}
            - Build: ${testStatus === 'success' ? 'Passed ✓' : 'Failed ✗'}

            ### Bundle Sizes
            - CJS: ${formatBytes(cjsSize)}
            - ESM: ${formatBytes(esmSize)}
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
